### ISSUE TITLE
ImportError: cannot import name 'cached_property' from 'functools'

### ISSUE THREAD

**Issue by Bugjudger** [enriccorona/SMPLicit#19]
Thanks for the awesome work. It works well in example.py. However, I meet a problem when using "python fit_SMPLicit.py".

```
Traceback (most recent call last):
  File "fit_SMPLicit.py", line 10, in <module>
    from utils import projection
  File "/home/xxx/workspace/VG/SMPLicit/fit_SMPLicit/utils/projection.py", line 3, in <module>
    import pyrender
  File "/home/xxx/anaconda3/envs/SMPLicit/lib/python3.7/site-packages/pyrender/__init__.py", line 10, in <module>
    from .scene import Scene
  File "/home/xxx/anaconda3/envs/SMPLicit/lib/python3.7/site-packages/pyrender/scene.py", line 7, in <module>
    import networkx as nx
  File "/home/xxx/anaconda3/envs/SMPLicit/lib/python3.7/site-packages/networkx-3.0b1-py3.7.egg/networkx/__init__.py", line 21, in <module>
    from networkx import classes
  File "/home/xxx/anaconda3/envs/SMPLicit/lib/python3.7/site-packages/networkx-3.0b1-py3.7.egg/networkx/classes/__init__.py", line 1, in <module>
    from .graph import Graph
  File "/home/xxx/anaconda3/envs/SMPLicit/lib/python3.7/site-packages/networkx-3.0b1-py3.7.egg/networkx/classes/graph.py", line 11, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property' from 'functools' (/home/xxx/anaconda3/envs/SMPLicit/lib/python3.7/functools.py)
```

Env: python3.7, kaolinv0.1.0, cuda10.2, torch1.10.1, SMPLicit0.0.1

Someone mention that it should use pthon3.8, however it conflicts with kaolinv0.1.
May someone help me?

**Comment by Bugjudger** [comment]
Finish~~ pip install pyrender==0.1.35
